version: "3.9"
services:
  crawler:
    build: .
    image: crawler-img
    volumes:
      - ./Soundcloud Crawler/log/:/code/log/
      - ./Pyspark ETL/data/:/code/data/
  ETL:
    image: spark-etl
    depends_on:
      - crawler
